name: Go

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build-and-test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.15

    - name: Build
      run: go build -v ./...

    - name: Run Tests
      run: go test -v ./... -covermode=count -coverprofile=coverage.out
      
    - name: Convert coverage to lcov
      uses: jandelgado/gcov2lcov-action@master
  
    - name: Run Coveralls
      uses: coverallsapp/github-action@master
      with:
        github-token: ${{ secrets.github_token }}
        path-to-lcov: coverage.lcov

    - name: Run golangci-lint
      uses: golangci/golangci-lint-action@v1.2.1
